### ISSUE TITLE
binary crashing when flow is not running properly

### ISSUE THREAD

**Issue by visualcookie** [fintory/flow-cov#9]
When running flow-cov it throws an unhandled promise rejection error.

Actual error from the log:
```
An error happened, while executing `flow-cov`:
Error: Error: Command failed: /Users/xxx/Fintory/xxx/node_modules/flow-bin/flow-osx-v0.91.0/flow status --json

(node:32500) UnhandledPromiseRejectionWarning: Error: Error: Error: Command failed: /Users/xxx/Fintory/xxx/node_modules/flow-bin/flow-osx-v0.91.0/flow status --json
    at logError (/Users/xxx/Fintory/xxx/node_modules/flow-cov/bin/utils/logError.js:31:9)
    at run (/Users/xxx/Fintory/xxx/node_modules/flow-cov/bin/index.js:25:12)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:32500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:32500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iduuck** [comment]
Can you please try out using the hotfix branch (#10)?

**Comment by visualcookie** [comment]
Tried out the hotfix and getting the following error now:

```
$ flow-cov
An error happened, while executing `flow-cov`:
TypeError: Cannot read property 'split' of undefined

(node:79178) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'split' of undefined
    at logError (/Users/xxx/Fintory/xxx/node_modules/flow-cov/bin/utils/logError.js:31:9)
    at run (/Users/xxx/Fintory/xxx/node_modules/flow-cov/bin/index.js:28:12)
    at Object.<anonymous> (/Users/xxx/Fintory/xxx/node_modules/flow-cov/bin/index.js:32:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
(node:79178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iduuck** [comment]
Just renamed the issue to cover the actual failure

**Comment by visualcookie** [comment]
Recent change does not fail anymore. 👍
